#!/usr/bin/env python3

'''
Example custom dynamic inventory script for Ansible, in Python.
'''

import os
import sys
import argparse
import json

class ExampleInventory(object):

    def __init__(self):
        self.inventory = {}
        self.read_cli_args()

        # Called with `--list`.
        if self.args.list:
            self.inventory = self.example_inventory()
        # Called with `--host [hostname]`.
        elif self.args.host:
            # Not implemented, since we return _meta info `--list`.
            self.inventory = self.empty_inventory()
        # If no groups or vars are present, return empty inventory.
        else:
            self.inventory = self.empty_inventory()

        print(json.dumps(self.inventory))

    # Example inventory for testing.
    def example_inventory(self):
        return {
            'varnish': {
                'hosts': [
                    'ec2-54-226-30-220.compute-1.amazonaws.com',
                ],
            },
            'php': {
                'hosts': [
                    'ec2-34-201-138-103.compute-1.amazonaws.com',
                    'ec2-54-242-73-207.compute-1.amazonaws.com',
                ],
            },
            'all': {
                'children': [
                    'varnish',
                    'php',
                ],
                'vars': {
                    'ansible_user': 'admin',
                    'ansible_ssh_private_key_file': '~/.ssh/devops-cloud.pem',
                    'example_variable': 'value'
                },
            },
            '_meta': {
                'hostvars': {
                    'ec2-54-226-30-220.compute-1.amazonaws.com': {
                        'varnish_host_specific_var': 'foo'
                    },
                },
            },
        }

    # Empty inventory for testing.
    def empty_inventory(self):
        return {'_meta': {'hostvars': {}}}

    # Read the command line args passed to the script.
    def read_cli_args(self):
        parser = argparse.ArgumentParser()
        parser.add_argument('--list', action = 'store_true')
        parser.add_argument('--host', action = 'store')
        self.args = parser.parse_args()

# Get the inventory.
ExampleInventory()
