#!/usr/bin/env php
<?php

/**
 * @file
 * Example custom dynamic inventory script for Ansible, in PHP.
 */

/**
 * Example inventory for testing.
 *
 * @return array
 *   Example inventory.
 */
function example_inventory() {
  return [
    'varnish' => [
      'hosts' => [
        'ec2-54-227-112-29.compute-1.amazonaws.com,',
      ],
    ],
    'php' => [
      'hosts' => [
        'ec2-18-207-144-9.compute-1.amazonaws.com',
        'ec2-34-229-10-231.compute-1.amazonaws.com',
      ],
    ],
    'all' => [
      'children' => [
        'varnish',
        'php',
      ],
      'vars' => [
        'ansible_user' => 'admin',
        'ansible_ssh_private_key_file' => '~/.ssh/devops-cloud.pem',
        'example_variable' => 'value',
      ],
    ],
    '_meta' => [
      'hostvars' => [
        'ec2-54-227-112-29.compute-1.amazonaws.com' => [
          'varnish_host_specific_var' => 'foo',
        ],
      ],
    ],
  ];
}

/**
 * Empty inventory for testing.
 *
 * @return array
 *   An empty inventory.
 */
function empty_inventory() {
  return ['_meta' => ['hostvars' => new stdClass()]];
}

/**
 * Get inventory.
 *
 * @param array $argv
 *   Array of command line arguments (as in $_SERVER['argv']).
 *
 * @return array
 *   Inventory of groups or vars, depending on arguments.
 */
function get_inventory($argv = []) {
  $inventory = new stdClass();

  // Called with `--list`.
  if (!empty($argv[1]) && $argv[1] == '--list') {
    $inventory = example_inventory();
  }
  // Called with `--host [hostname]`.
  elseif ((!empty($argv[1]) && $argv[1] == '--host') && !empty($argv[2])) {
    // Not implemented, since we return _meta info `--list`.
    $inventory = empty_inventory();
  }
  // If no groups or vars are present, return an empty inventory.
  else {
    $inventory = empty_inventory();
  }

  print json_encode($inventory);
}

// Get the inventory.
get_inventory($_SERVER['argv']);
